CREATE TABLE `unit` (
  `id` int(11) NOT NULL DEFAULT '0',
  `unitType` varchar(20) NOT NULL,
  `unitClass` varchar(20) NOT NULL,
  `race` varchar(20) NOT NULL,
  `damageMinimal` int(11) NOT NULL,
  `damageMaximum` int(11) NOT NULL,
  `hitpoints` int(11) NOT NULL,
  `weight` int(11) NOT NULL,
  `movementRange` int(11) NOT NULL,
  `attackRange` int(11) NOT NULL,
  `initiative` int(11) NOT NULL,
  `strikeBack` int(11) NOT NULL,
  `attackBonus_1_Type` varchar(20) DEFAULT NULL,
  `attackBonus_1_Value` double DEFAULT NULL,
  `defensBonus_1_Type` varchar(20) DEFAULT NULL,
  `defenseBonus_1_Value` double DEFAULT NULL,
  `attackBonus_2_Type` varchar(20) DEFAULT NULL,
  `attackBonus_2_Value` double DEFAULT NULL,
  `defensBonus_2_Type` varchar(20) DEFAULT NULL,
  `defenseBonus_2_Value` double DEFAULT NULL,
  `specialAbilityType` varchar(20) DEFAULT NULL,
  `specialAbilityValue` double DEFAULT NULL,
  `promotion` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8